
CREATE TABLE FORM_SET (
  FORM_SET_SEQ int NOT NULL AUTO_INCREMENT COMMENT '폼게시판 번호',
  FORM_SET_NAME varchar(200) DEFAULT NULL COMMENT '폼게시판 명',
  FORM_SET_TYPE varchar(3) DEFAULT NULL COMMENT '폼게시판 타입(100,200,300)',
  FORM_SET_SKIN varchar(10) DEFAULT NULL COMMENT '폼 디자인(001,002...)',
  TARGET_TABLE_NAME varchar(30) DEFAULT NULL COMMENT '데이터 저장 테이블명',
  REG_DATE DATETIME DEFAULT NULL COMMENT '등록일',
  MOD_DATE DATETIME DEFAULT NULL COMMENT '수정일',
  DIST_COMP VARCHAR(1) DEFAULT 'N' NULL COMMENT '배포완료여부'
);

CREATE TABLE FORM_ITEM (
  FORM_ITEM_SEQ int NOT NULL AUTO_INCREMENT COMMENT '폼 구성 항목 번호',
  FORM_ITEM_NAME varchar(200) DEFAULT NULL COMMENT '항목 명',
  FORM_ITEM_TYPE varchar(20) DEFAULT NULL COMMENT '항목 타입(10,20,30)',
  FORM_ITEM_LIST varchar(1) DEFAULT NULL COMMENT '목록 출력 여부',
  FORM_ITEM_LIST_ORDER int DEFAULT NULL COMMENT '목록 출력 순서',
  FORM_ITEM_VIEW varchar(1) DEFAULT NULL COMMENT '입력(보기) 출력 여부',
  FORM_ITEM_VIEW_ORDER int DEFAULT NULL COMMENT '입력(보기) 출력 순서',
  FORM_ITEM_VIEW_TYPE varchar(10) DEFAULT NULL COMMENT '출력 형식(수평-hor,수직-ver)',
  FORM_ITEM_DES varchar(500) DEFAULT NULL COMMENT '항목 설명(description)',
  REG_DATE DATETIME DEFAULT NULL COMMENT '등록일',
  MOD_DATE DATETIME DEFAULT NULL COMMENT '수정일',
  FORM_SET_SEQ int NOT NULL COMMENT '폼게시판 번호',
  TB_COLUMN_NAME varchar(100) DEFAULT NULL COMMENT '테이블 컬럼명(자동생성)',
  ITEM_HTML varchar(800) DEFAULT NULL COMMENT '항목 구성 HTML',
  ITEM_JSON varchar(500) DEFAULT NULL COMMENT '항목 구성 JSON'
);

CREATE TABLE FORM_FIELD (
  FORM_FIELD_SEQ int NOT NULL AUTO_INCREMENT COMMENT '폼 항목 필드 번호',
  FORM_FIELD_TEXT varchar(200) DEFAULT NULL COMMENT '필드 명(text,textrare->동작 없음, radio,checkbox,selectbox->필드명)',
  FORM_FIELD_VALUE varchar(20) DEFAULT NULL COMMENT '필드 값(text,textrare,radio,checkbox,selectbox->value)',
  FORM_FILED_DEFAULT varchar(20) DEFAULT NULL COMMENT '필드 기본 값(text,textarea->value우선 / radio,checkbox,selectbox->기본선택)',
  FORM_FIELD_PHD varchar(200) DEFAULT NULL COMMENT '필드 힌트(placeholder)',
  FORM_FIELD_DES varchar(500) DEFAULT NULL COMMENT '필드 설명(description)',
  REG_DATE DATETIME DEFAULT NULL COMMENT '등록일',
  MOD_DATE DATETIME DEFAULT NULL COMMENT '수정일',
  FORM_ITEM_SEQ int NOT NULL COMMENT '폼 구성 항목 번호'
);

CREATE TABLE FORM_AUTH (
  AUTH_SEQ int NOT NULL AUTO_INCREMENT COMMENT '권한 번호',
  AUTH_NAME varchar(200) DEFAULT NULL COMMENT '권한명',
  AUTH_LIST varchar(20) DEFAULT NULL COMMENT '목록 여부',
  AUTH_WRITE varchar(20) DEFAULT NULL COMMENT '글쓰기 여부',
  AUTH_VIEW varchar(200) DEFAULT NULL COMMENT '상세보기 여부',
  AUTH_FILE_DOWN varchar(500) DEFAULT NULL COMMENT '다운로드 여부',
  REG_DATE DATETIME DEFAULT NULL COMMENT '등록일',
  MOD_DATE DATETIME DEFAULT NULL COMMENT '수정일',
  FORM_SET_SEQ int NOT NULL COMMENT '폼게시판 번호'
);
